framework = "LocalAuthentication"
crate = "objc2-local-authentication"
required-crates = ["objc2", "objc2-foundation"]
macos = "10.10"
maccatalyst = "13.0"
ios = "8.0"
watchos = "9.0"
visionos = "1.0"

# Uses defines
enum.LABiometryType.use-value = true
enum.LABiometryType.constants.LABiometryNone.use-value = false
enum.LACompanionType.use-value = true
enum.LAPolicy.use-value = true
enum.LACredentialType.use-value = true
enum.LAError.use-value = true
