framework = "GameController"
crate = "objc2-game-controller"
required-crates = ["objc2", "objc2-foundation"]
macos = "10.9"
maccatalyst = "13.0"
ios = "7.0"
tvos = "9.0"
visionos = "1.0"

external.CHHapticEngine.module = "CoreHaptics.CHHapticEngine"

# Needs `IOHIDDeviceRef` from IOKit
class.GCController.methods."supportsHIDDevice:".skipped = true
