framework = "PreferencePanes"
crate = "objc2-preference-panes"
required-crates = ["objc2", "objc2-foundation"]
macos = "10.1"
maccatalyst = "14.0"

# References static in constant.
const.kNSPrefPaneHelpMenuInfoPListKey.skipped = true
const.kNSPrefPaneHelpMenuTitleKey.skipped = true
const.kNSPrefPaneHelpMenuAnchorKey.skipped = true
