framework = "QuickLookThumbnailing"
crate = "objc2-quick-look-thumbnailing"
required-crates = ["objc2", "objc2-foundation"]
macos = "10.15"
maccatalyst = "13.0"
ios = "13.0"
visionos = "1.0"

external.UIImage.module = "UIKit.UIImage"
external.NSImage.module = "AppKit.NSImage"
