framework = "CoreGraphics"
crate = "objc2-core-graphics"
required-crates = []
custom-lib-rs = true
macos = "10.8"
maccatalyst = "13.0"
ios = "2.0"
tvos = "9.0"
watchos = "2.0"
visionos = "1.0"

external.MTLDevice.module = "Metal.MTLDevice"

# Needs dispatch_queue_t from libdispatch
fn.CGDisplayStreamCreateWithDispatchQueue.skipped = true

# CF_RELEASES_ARGUMENT / cf_consumed, requires manual handling
fn.CGColorSpaceRelease.skipped = true

# CoreGraphics defines this for some reason?
typedef.IOSurfaceRef.skipped = true
struct.__IOSurface.skipped = true

# Needs io_service_t from the kernel
fn.CGDisplayIOServicePort.skipped = true

# Needs core::ffi::VaList, currently unstable
fn.CGColorConversionInfoCreateFromListWithArguments.skipped = true

# Unknown how to handle the calling convention here?
fn.CGColorSpaceCreateCalibratedGray.skipped = true
fn.CGColorSpaceCreateCalibratedRGB.skipped = true
fn.CGColorSpaceCreateLab.skipped = true
fn.CGFontCreatePostScriptSubset.skipped = true
fn.CGFontCreatePostScriptEncoding.skipped = true

# Calculation of these constants overflow, so we must use a larger type.
static.kCGFontIndexMax.skipped = true
static.kCGFontIndexInvalid.skipped = true
