framework = "CoreFoundation"
crate = "objc2-core-foundation"
required-crates = []
custom-lib-rs = true
macos = "10.0"
maccatalyst = "13.0"
ios = "2.0"
tvos = "9.0"
watchos = "2.0"
visionos = "1.0"
gnustep = true

# Uses variadics
fn.CFStringCreateWithFormatAndArguments.skipped = true
fn.CFStringCreateStringWithValidatedFormatAndArguments.skipped = true
fn.CFStringAppendFormatAndArguments.skipped = true

# Name clash with containing module
enum.__CFByteOrder.skipped = true

# Needs dispatch_queue_t
fn.CFMessagePortSetDispatchQueue.skipped = true
fn.CFReadStreamSetDispatchQueue.skipped = true
fn.CFWriteStreamSetDispatchQueue.skipped = true
fn.CFReadStreamCopyDispatchQueue.skipped = true
fn.CFWriteStreamCopyDispatchQueue.skipped = true

# Needs FSRef from CoreServices
fn.CFURLCreateFromFSRef.skipped = true
fn.CFURLGetFSRef.skipped = true

# Needs acl_t, which is not exposed by libc
fn.CFFileSecurityCopyAccessControlList.skipped = true
fn.CFFileSecuritySetAccessControlList.skipped = true

# Different definition depending on pointer width
typedef.CGFloat.skipped = true

# Custom definitions for slightly better docs now
struct.CGPoint.skipped = true
struct.CGSize.skipped = true
struct.CGRect.skipped = true

# Custom definition because it's special
typedef.CFTypeRef.skipped = true

# Implementation details
fn.__CFRangeMake.skipped = true
fn.__CFStringMakeConstantString.skipped = true

# Differs based on architecture
typedef.CFBundleRefNum.skipped = true
typedef.CFTypeID.skipped = true
typedef.CFOptionFlags.skipped = true
typedef.CFHashCode.skipped = true
typedef.CFIndex.skipped = true

# Custom-defined since they require manual handling.
# Use `CFRetained` to access these.
fn.CFAutorelease.skipped = true
fn.CFRetain.skipped = true
fn.CFRelease.skipped = true
fn.CFMakeCollectable.skipped = true

# Dependent on target endianness
fn.CFByteOrderGetCurrent.skipped = true
fn.CFSwapInt16BigToHost.skipped = true
fn.CFSwapInt32BigToHost.skipped = true
fn.CFSwapInt64BigToHost.skipped = true
fn.CFSwapInt16HostToBig.skipped = true
fn.CFSwapInt32HostToBig.skipped = true
fn.CFSwapInt64HostToBig.skipped = true
fn.CFSwapInt16LittleToHost.skipped = true
fn.CFSwapInt32LittleToHost.skipped = true
fn.CFSwapInt64LittleToHost.skipped = true
fn.CFSwapInt16HostToLittle.skipped = true
fn.CFSwapInt32HostToLittle.skipped = true
fn.CFSwapInt64HostToLittle.skipped = true
fn.CFConvertFloat32HostToSwapped.skipped = true
fn.CFConvertFloat32SwappedToHost.skipped = true
fn.CFConvertFloat64HostToSwapped.skipped = true
fn.CFConvertFloat64SwappedToHost.skipped = true
fn.CFConvertFloatHostToSwapped.skipped = true
fn.CFConvertFloatSwappedToHost.skipped = true
fn.CFConvertDoubleHostToSwapped.skipped = true
fn.CFConvertDoubleSwappedToHost.skipped = true

fn.CFGetTypeID.unsafe = false
fn.CFCopyTypeIDDescription.unsafe = false
fn.CFGetRetainCount.unsafe = false
fn.CFEqual.unsafe = false
fn.CFHash.unsafe = false
fn.CFCopyDescription.unsafe = false
