framework = "FinderSync"
crate = "objc2-finder-sync"
required-crates = ["objc2", "objc2-foundation"]
macos = "10.10"

# Both a protocol and a class, so we use Swift's naming scheme
protocol.FIFinderSync.renamed = "FIFinderSyncProtocol"
