framework = "MediaPlayer"
crate = "objc2-media-player"
required-dependencies = ["objc2-foundation"]
macos = "10.12.1"
maccatalyst = "13.0"
ios = "2.0"
tvos = "9.0"
watchos = "5.0"
visionos = "1.0"

external.NSImage.module = "AppKit.NSImage"
