[package]
name = "test_ns_string"
version = "0.1.0"
edition.workspace = true
publish = false

[lib]
path = "lib.rs"

[dependencies]
objc2-foundation = { path = "../../../../framework-crates/objc2-foundation", default-features = false, features = [
    "std",
    "block2",
    "NSString",
]}

[features]
# Runtime
gnustep-1-7 = ["objc2-foundation/gnustep-1-7"]
gnustep-1-8 = ["gnustep-1-7", "objc2-foundation/gnustep-1-8"]
gnustep-1-9 = ["gnustep-1-8", "objc2-foundation/gnustep-1-9"]
gnustep-2-0 = ["gnustep-1-9", "objc2-foundation/gnustep-2-0"]
gnustep-2-1 = ["gnustep-2-0", "objc2-foundation/gnustep-2-1"]

# Hack
assembly-features = ["objc2-foundation/unstable-static-nsstring"]

[package.metadata.release]
release = false
