framework = "BusinessChat"
crate = "objc2-business-chat"
required-crates = ["objc2", "objc2-foundation", "objc2-app-kit"]
macos = "10.14"
maccatalyst = "13.0"               # Unsure
ios = "11.0"                       # Unsure
