framework = "VideoSubscriberAccount"
crate = "objc2-video-subscriber-account"
required-crates = ["objc2", "objc2-foundation"]
macos = "10.14"
ios = "10.0"
tvos = "10.0"
visionos = "1.0"

external.UIViewController.module = "UIKit.UIViewController"
