[features]
VNObservation = [
    "objc2-foundation/NSArray",
    "objc2-foundation/NSData",
    "objc2-foundation/NSDictionary",
    "objc2-foundation/NSError",
    "objc2-foundation/NSIndexPath",
    "objc2-foundation/NSIndexSet",
    "objc2-foundation/NSObject",
    "objc2-foundation/NSRange", # Added
    "objc2-foundation/NSString",
    "objc2-foundation/NSUUID",
    "objc2-foundation/NSValue",
]
