framework = "Vision"
crate = "objc2-vision"
required-dependencies = ["objc2-foundation"]
custom-lib-rs = true
macos = "10.13"
maccatalyst = "13.0"
ios = "11.0"
tvos = "11.0"
visionos = "1.0"

external.CIBarcodeDescriptor.module = "CoreImage.CIBarcodeDescriptor"
external.CIImage.module = "CoreImage.CIImage"

# Needs SIMD types, which we cannot yet describe the ABI of in Rust
fn.VNNormalizedFaceBoundingBoxPointForLandmarkPoint.skipped = true
fn.VNImagePointForFaceLandmarkPoint.skipped = true
class.VNPoint3D.methods."initWithPosition:".skipped = true
class.VNPoint3D.methods.position.skipped = true
class.VNContour.methods.normalizedPoints.skipped = true
class.VNGeometryUtils.methods."boundingCircleForSIMDPoints:pointCount:error:".skipped = true
class.VNHumanBodyRecognizedPoint3D.methods.localPosition.skipped = true
class.VNTrajectoryObservation.methods.equationCoefficients.skipped = true
class.VNImageHomographicAlignmentObservation.methods.warpTransform.skipped = true
class.VNHumanBodyPose3DObservation.methods.cameraOriginMatrix.skipped = true
class.VNHumanBodyPose3DObservation.methods."getCameraRelativePosition:forJointName:error:".skipped = true

# error: unknown error result type
class.VNTrackingRequest.methods."supportedNumberOfTrackersAndReturnError:".skipped = true

# apinotes are being weird here
class.VNRecognizedText.methods."boundingBoxForRange:error:".skipped = true

# Needs CoreMedia
class.VNDetectHumanBodyPose3DRequest.methods."initWithFrameAnalysisSpacing:completionHandler:".skipped = true
class.VNDetectTrajectoriesRequest.methods."initWithFrameAnalysisSpacing:completionHandler:".skipped = true
class.VNDetectTrajectoriesRequest.methods."initWithFrameAnalysisSpacing:trajectoryLength:completionHandler:".skipped = true
class.VNDetectTrajectoriesRequest.methods.targetFrameTime.skipped = true
class.VNDetectTrajectoriesRequest.methods."setTargetFrameTime:".skipped = true
class.VNGeneratePersonSegmentationRequest.methods."initWithFrameAnalysisSpacing:completionHandler:".skipped = true
class.VNObservation.methods.timeRange.skipped = true
class.VNImageRequestHandler.methods."initWithCMSampleBuffer:options:".skipped = true
class.VNSequenceRequestHandler.methods."performRequests:onCMSampleBuffer:error:".skipped = true
class.VNStatefulRequest.methods."initWithFrameAnalysisSpacing:completionHandler:".skipped = true
class.VNStatefulRequest.methods.frameAnalysisSpacing.skipped = true
class.VNTargetedImageRequest.methods."initWithTargetedCMSampleBuffer:options:".skipped = true
class.VNTargetedImageRequest.methods."initWithTargetedCMSampleBuffer:options:completionHandler:".skipped = true
class.VNVideoProcessor.methods."analyzeTimeRange:error:".skipped = true
class.VNVideoProcessor.methods."analyzeWithTimeRange:error:".skipped = true
class.VNImageRequestHandler.methods."initWithCMSampleBuffer:orientation:options:".skipped = true
class.VNImageRequestHandler.methods."initWithCMSampleBuffer:depthData:orientation:options:".skipped = true
class.VNSequenceRequestHandler.methods."performRequests:onCMSampleBuffer:orientation:error:".skipped = true
class.VNTargetedImageRequest.methods."initWithTargetedCMSampleBuffer:orientation:options:".skipped = true
class.VNTargetedImageRequest.methods."initWithTargetedCMSampleBuffer:orientation:options:completionHandler:".skipped = true

# Needs CoreVideo to have proper retain semantics
class.VNInstanceMaskObservation.methods."generateMaskForInstances:error:".skipped = true
class.VNInstanceMaskObservation.methods."generateMaskedImageOfInstances:fromRequestHandler:croppedToInstancesExtent:error:".skipped = true
class.VNInstanceMaskObservation.methods."generateScaledMaskForImageForInstances:fromRequestHandler:error:".skipped = true

# Needs `CGImagePropertyOrientation` from `ImageIO`
class.VNImageRequestHandler.methods."initWithCVPixelBuffer:orientation:options:".skipped = true
class.VNImageRequestHandler.methods."initWithCVPixelBuffer:depthData:orientation:options:".skipped = true
class.VNImageRequestHandler.methods."initWithCGImage:orientation:options:".skipped = true
class.VNImageRequestHandler.methods."initWithCIImage:orientation:options:".skipped = true
class.VNImageRequestHandler.methods."initWithURL:orientation:options:".skipped = true
class.VNImageRequestHandler.methods."initWithData:orientation:options:".skipped = true
class.VNSequenceRequestHandler.methods."performRequests:onCVPixelBuffer:orientation:error:".skipped = true
class.VNSequenceRequestHandler.methods."performRequests:onCGImage:orientation:error:".skipped = true
class.VNSequenceRequestHandler.methods."performRequests:onCIImage:orientation:error:".skipped = true
class.VNSequenceRequestHandler.methods."performRequests:onImageURL:orientation:error:".skipped = true
class.VNSequenceRequestHandler.methods."performRequests:onImageData:orientation:error:".skipped = true
class.VNTargetedImageRequest.methods."initWithTargetedCVPixelBuffer:orientation:options:".skipped = true
class.VNTargetedImageRequest.methods."initWithTargetedCVPixelBuffer:orientation:options:completionHandler:".skipped = true
class.VNTargetedImageRequest.methods."initWithTargetedCGImage:orientation:options:".skipped = true
class.VNTargetedImageRequest.methods."initWithTargetedCGImage:orientation:options:completionHandler:".skipped = true
class.VNTargetedImageRequest.methods."initWithTargetedCIImage:orientation:options:".skipped = true
class.VNTargetedImageRequest.methods."initWithTargetedCIImage:orientation:options:completionHandler:".skipped = true
class.VNTargetedImageRequest.methods."initWithTargetedImageURL:orientation:options:".skipped = true
class.VNTargetedImageRequest.methods."initWithTargetedImageURL:orientation:options:completionHandler:".skipped = true
class.VNTargetedImageRequest.methods."initWithTargetedImageData:orientation:options:".skipped = true
class.VNTargetedImageRequest.methods."initWithTargetedImageData:orientation:options:completionHandler:".skipped = true


###
### Safety
###

class.VNImageRequestHandler.methods."initWithData:options:".unsafe = false
class.VNImageRequestHandler.methods."performRequests:error:".unsafe = false

class.VNRecognizedText.methods.string.unsafe = false
class.VNRecognizedText.methods.confidence.unsafe = false

class.VNRecognizedTextObservation.methods."topCandidates:".unsafe = false

class.VNRecognizeTextRequest.methods.new.unsafe = false
class.VNRecognizeTextRequest.methods.results.unsafe = false
class.VNRecognizeTextRequest.methods."setRecognitionLanguages:".unsafe = false
class.VNRecognizeTextRequest.methods.usesLanguageCorrection.unsafe = false
class.VNRecognizeTextRequest.methods.customWords.unsafe = false
class.VNRecognizeTextRequest.methods."setCustomWords:".unsafe = false
class.VNRecognizeTextRequest.methods.recognitionLevel.unsafe = false
class.VNRecognizeTextRequest.methods."setRecognitionLevel:".unsafe = false
class.VNRecognizeTextRequest.methods."setUsesLanguageCorrection:".unsafe = false
class.VNRecognizeTextRequest.methods.automaticallyDetectsLanguage.unsafe = false
class.VNRecognizeTextRequest.methods."setAutomaticallyDetectsLanguage:".unsafe = false
class.VNRecognizeTextRequest.methods.minimumTextHeight.unsafe = false
class.VNRecognizeTextRequest.methods."setMinimumTextHeight:".unsafe = false
