framework = "Vision"
crate = "objc2-vision"
required-crates = ["objc2", "objc2-foundation"]
custom-lib-rs = true
macos = "10.13"
maccatalyst = "13.0"
ios = "11.0"
tvos = "11.0"
visionos = "1.0"

external.CIBarcodeDescriptor.module = "CoreImage.CIBarcodeDescriptor"
external.CIImage.module = "CoreImage.CIImage"

# error: unknown error result type
class.VNTrackingRequest.methods."supportedNumberOfTrackersAndReturnError:".skipped = true

# apinotes are being weird here
class.VNRecognizedText.methods."boundingBoxForRange:error:".skipped = true

# Needs CoreVideo to have proper retain semantics
class.VNInstanceMaskObservation.methods."generateMaskForInstances:error:".skipped = true
class.VNInstanceMaskObservation.methods."generateMaskedImageOfInstances:fromRequestHandler:croppedToInstancesExtent:error:".skipped = true
class.VNInstanceMaskObservation.methods."generateScaledMaskForImageForInstances:fromRequestHandler:error:".skipped = true

# Needs `CGImagePropertyOrientation` from `ImageIO`
class.VNImageRequestHandler.methods."initWithCVPixelBuffer:orientation:options:".skipped = true
class.VNImageRequestHandler.methods."initWithCVPixelBuffer:depthData:orientation:options:".skipped = true
class.VNImageRequestHandler.methods."initWithCGImage:orientation:options:".skipped = true
class.VNImageRequestHandler.methods."initWithCIImage:orientation:options:".skipped = true
class.VNImageRequestHandler.methods."initWithURL:orientation:options:".skipped = true
class.VNImageRequestHandler.methods."initWithData:orientation:options:".skipped = true
class.VNSequenceRequestHandler.methods."performRequests:onCVPixelBuffer:orientation:error:".skipped = true
class.VNSequenceRequestHandler.methods."performRequests:onCGImage:orientation:error:".skipped = true
class.VNSequenceRequestHandler.methods."performRequests:onCIImage:orientation:error:".skipped = true
class.VNSequenceRequestHandler.methods."performRequests:onImageURL:orientation:error:".skipped = true
class.VNSequenceRequestHandler.methods."performRequests:onImageData:orientation:error:".skipped = true
class.VNTargetedImageRequest.methods."initWithTargetedCVPixelBuffer:orientation:options:".skipped = true
class.VNTargetedImageRequest.methods."initWithTargetedCVPixelBuffer:orientation:options:completionHandler:".skipped = true
class.VNTargetedImageRequest.methods."initWithTargetedCGImage:orientation:options:".skipped = true
class.VNTargetedImageRequest.methods."initWithTargetedCGImage:orientation:options:completionHandler:".skipped = true
class.VNTargetedImageRequest.methods."initWithTargetedCIImage:orientation:options:".skipped = true
class.VNTargetedImageRequest.methods."initWithTargetedCIImage:orientation:options:completionHandler:".skipped = true
class.VNTargetedImageRequest.methods."initWithTargetedImageURL:orientation:options:".skipped = true
class.VNTargetedImageRequest.methods."initWithTargetedImageURL:orientation:options:completionHandler:".skipped = true
class.VNTargetedImageRequest.methods."initWithTargetedImageData:orientation:options:".skipped = true
class.VNTargetedImageRequest.methods."initWithTargetedImageData:orientation:options:completionHandler:".skipped = true
class.VNImageRequestHandler.methods."initWithCMSampleBuffer:orientation:options:".skipped = true
class.VNImageRequestHandler.methods."initWithCMSampleBuffer:depthData:orientation:options:".skipped = true
class.VNSequenceRequestHandler.methods."performRequests:onCMSampleBuffer:orientation:error:".skipped = true
class.VNTargetedImageRequest.methods."initWithTargetedCMSampleBuffer:orientation:options:".skipped = true
class.VNTargetedImageRequest.methods."initWithTargetedCMSampleBuffer:orientation:options:completionHandler:".skipped = true



###
### Safety
###

class.VNImageRequestHandler.methods."initWithData:options:".unsafe = false
class.VNImageRequestHandler.methods."performRequests:error:".unsafe = false

class.VNRecognizedText.methods.string.unsafe = false
class.VNRecognizedText.methods.confidence.unsafe = false

class.VNRecognizedTextObservation.methods."topCandidates:".unsafe = false

class.VNRecognizeTextRequest.methods.new.unsafe = false
class.VNRecognizeTextRequest.methods.results.unsafe = false
class.VNRecognizeTextRequest.methods."setRecognitionLanguages:".unsafe = false
class.VNRecognizeTextRequest.methods.usesLanguageCorrection.unsafe = false
class.VNRecognizeTextRequest.methods.customWords.unsafe = false
class.VNRecognizeTextRequest.methods."setCustomWords:".unsafe = false
class.VNRecognizeTextRequest.methods.recognitionLevel.unsafe = false
class.VNRecognizeTextRequest.methods."setRecognitionLevel:".unsafe = false
class.VNRecognizeTextRequest.methods."setUsesLanguageCorrection:".unsafe = false
class.VNRecognizeTextRequest.methods.automaticallyDetectsLanguage.unsafe = false
class.VNRecognizeTextRequest.methods."setAutomaticallyDetectsLanguage:".unsafe = false
class.VNRecognizeTextRequest.methods.minimumTextHeight.unsafe = false
class.VNRecognizeTextRequest.methods."setMinimumTextHeight:".unsafe = false
