framework = "Vision"
crate = "objc2-vision"
required-crates = ["objc2", "objc2-foundation"]
custom-lib-rs = true
macos = "10.13"
maccatalyst = "13.0"
ios = "11.0"
tvos = "11.0"
visionos = "1.0"

external.CIBarcodeDescriptor.module = "CoreImage.CIBarcodeDescriptor"
external.CIImage.module = "CoreImage.CIImage"
external.AVDepthData.module = "AVFoundation.AVDepthData"

# error: unknown error result type
class.VNTrackingRequest.methods."supportedNumberOfTrackersAndReturnError:".skipped = true

# apinotes are being weird here
class.VNRecognizedText.methods."boundingBoxForRange:error:".skipped = true

# Needs CoreVideo to have proper retain semantics
class.VNInstanceMaskObservation.methods."generateMaskForInstances:error:".skipped = true
class.VNInstanceMaskObservation.methods."generateMaskedImageOfInstances:fromRequestHandler:croppedToInstancesExtent:error:".skipped = true
class.VNInstanceMaskObservation.methods."generateScaledMaskForImageForInstances:fromRequestHandler:error:".skipped = true



###
### Safety
###

class.VNImageRequestHandler.methods."initWithData:options:".unsafe = false
class.VNImageRequestHandler.methods."performRequests:error:".unsafe = false

class.VNRecognizedText.methods.string.unsafe = false
class.VNRecognizedText.methods.confidence.unsafe = false

class.VNRecognizedTextObservation.methods."topCandidates:".unsafe = false

class.VNRecognizeTextRequest.methods.new.unsafe = false
class.VNRecognizeTextRequest.methods.results.unsafe = false
class.VNRecognizeTextRequest.methods."setRecognitionLanguages:".unsafe = false
class.VNRecognizeTextRequest.methods.usesLanguageCorrection.unsafe = false
class.VNRecognizeTextRequest.methods.customWords.unsafe = false
class.VNRecognizeTextRequest.methods."setCustomWords:".unsafe = false
class.VNRecognizeTextRequest.methods.recognitionLevel.unsafe = false
class.VNRecognizeTextRequest.methods."setRecognitionLevel:".unsafe = false
class.VNRecognizeTextRequest.methods."setUsesLanguageCorrection:".unsafe = false
class.VNRecognizeTextRequest.methods.automaticallyDetectsLanguage.unsafe = false
class.VNRecognizeTextRequest.methods."setAutomaticallyDetectsLanguage:".unsafe = false
class.VNRecognizeTextRequest.methods.minimumTextHeight.unsafe = false
class.VNRecognizeTextRequest.methods."setMinimumTextHeight:".unsafe = false
