[package]
name = "objc2-proc-macros"
# Remember to update html_root_url in lib.rs
version = "0.1.3"
authors = ["Mads Marquart <mads@marquart.dk>", "Calvin Watford"]
description = "Procedural macros for the objc2 project"
keywords = ["objective-c", "macos", "ios", "proc-macro"]
categories = [
    "development-tools",
    "os::macos-apis",
]
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license = "Zlib OR Apache-2.0 OR MIT"

[lib]
proc-macro = true

[lints]
workspace = true

[features]
default = []

# Runtime selection (for future compatibility)
gnustep-1-7 = []
gnustep-1-8 = ["gnustep-1-7"]
gnustep-1-9 = ["gnustep-1-8"]
gnustep-2-0 = ["gnustep-1-9"]
gnustep-2-1 = ["gnustep-2-0"]

[package.metadata.docs.rs]
default-target = "aarch64-apple-darwin"
targets = [
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    "aarch64-apple-ios",
    "aarch64-apple-tvos",
    "aarch64-apple-watchos",
    "aarch64-apple-ios-macabi",
    "aarch64-apple-visionos",
    "x86_64-unknown-linux-gnu",
    "i686-unknown-linux-gnu",
]

[package.metadata.release]
shared-version = false
tag-prefix = "objc-proc-macros"
enable-features = []
