framework = "Photos"
crate = "objc2-photos"
required-crates = ["objc2", "objc2-foundation"]
custom-lib-rs = true
macos = "10.11"
maccatalyst = "13.0"
ios = "8.0"
tvos = "10.0"
visionos = "1.0"

external.NSImage.module = "AppKit.NSImage"
external.UIImage.module = "UIKit.UIImage"

# Needs `CGImagePropertyOrientation` from `ImageIO`
class.PHLivePhotoEditingContext.methods.orientation.skipped = true
class.PHImageManager.methods."requestImageDataAndOrientationForAsset:options:resultHandler:".skipped = true
# Needs `UIImageOrientation` from `UIKit`
class.PHImageManager.methods."requestImageDataForAsset:options:resultHandler:".skipped = true
