framework = "StoreKit"
crate = "objc2-store-kit"
required-crates = ["objc2", "objc2-foundation"]
macos = "10.7"
maccatalyst = "13.0"
ios = "3.0"
tvos = "9.0"
watchos = "6.2"
visionos = "1.0"

# Set counterparts
class.SKPayment.counterpart = "MutableSubclass(StoreKit.SKPayment.SKMutablePayment)"
class.SKMutablePayment.counterpart = "ImmutableSuperclass(StoreKit.SKPayment.SKPayment)"
