framework = "CoreBluetooth"
crate = "objc2-core-bluetooth"
required-crates = ["objc2", "objc2-foundation"]
macos = "10.10"
maccatalyst = "13.0"
ios = "5.0"
tvos = "9.0"
watchos = "4.0"
visionos = "1.0"
