framework = "GameKit"
crate = "objc2-game-kit"
required-crates = ["objc2", "objc2-foundation"]
macos = "10.8"
maccatalyst = "13.0"
ios = "3.0"
tvos = "9.0"
watchos = "3.0"
visionos = "1.0"

# Marked as API_UNAVAILABLE in a category, so we hit the duplicate checking
class.GKLeaderboard.methods.init.skipped = true
class.GKLeaderboard.methods.new.skipped = true
