framework = "IOSurface"
crate = "objc2-io-surface"
required-crates = []
custom-lib-rs = true
macos = "10.6"
maccatalyst = "13.0"
ios = "11.0"
tvos = "11.0"
visionos = "1.0"

# Needs xpc_object_t
fn.IOSurfaceCreateXPCObject.skipped = true
fn.IOSurfaceLookupFromXPCObject.skipped = true

# Needs task_id_token_t
fn.IOSurfaceSetOwnershipIdentity.skipped = true

# Defined in other crates too, so needs manual definition
typedef.IOSurfaceRef.skipped = true
struct.__IOSurface.skipped = true
