framework = "PushToTalk"
crate = "objc2-push-to-talk"
required-crates = ["objc2", "objc2-foundation"]
maccatalyst = "16.0"
ios = "16.0"
# The framework is _present_ in the macOS SDK, but it's completely empty

external.UIImage.module = "UIKit.UIImage"
external.AVAudioSession.module = "AVFAudio.AVAudioSession"
