framework = "MetalPerformanceShadersGraph"
crate = "objc2-metal-performance-shaders-graph"
required-crates = ["objc2", "objc2-foundation", "objc2-metal"]
macos = "11.0"
maccatalyst = "14.0"
ios = "14.0"
tvos = "14.0"
visionos = "1.0"
