framework = "CallKit"
crate = "objc2-call-kit"
required-crates = ["objc2", "objc2-foundation"]
custom-lib-rs = true
macos = "13.0"
maccatalyst = "13.0"
ios = "10.0"
watchos = "9.0"
visionos = "1.0"

external.AVAudioSession.module = "AVFAudio.AVAudioSession"
