framework = "AVRouting"
crate = "objc2-av-routing"
required-crates = ["objc2", "objc2-foundation"]
macos = "13.0"
maccatalyst = "16.0"
ios = "16.0"
visionos = "1.0"

external.UTType.module = "UniformTypeIdentifiers.UTType"

# Needs nw_endpoint_t from Network
class.AVCustomDeviceRoute.methods.networkEndpoint.skipped = true
