framework = "MetalPerformanceShaders"
crate = "objc2-metal-performance-shaders"
required-crates = ["bitflags", "objc2", "objc2-foundation", "objc2-metal"]
custom-lib-rs = true
macos = "10.13"
maccatalyst = "13.0"
ios = "9.0"
tvos = "9.0"
visionos = "1.0"

# Defined in both MPSCore.MPSImage and MPSCore.MPSNDArray
typedef.MPSImageBatch.skipped = true

# tries to derive with `PartialEq` which fails because of `Bool` fields
# struct.MPSImageHistogramInfo.skipped = true

# Has a union field, but we'd rather have it as just a struct
struct._MPSPackedFloat3.skipped = true
typedef.MPSPackedFloat3.skipped = true

# Array in static is unimplemented
static.MPSFunctionConstantNoneArray.skipped = true

# Unclear how to handle these (non-null return error methods).
class.MPSKeyedUnarchiver.methods."initForReadingFromData:error:".skipped = true
class.MPSKeyedUnarchiver.methods."initForReadingFromData:device:error:".skipped = true
