framework = "__builtin__"
crate = "__builtin__"
required-crates = []
link = false
skipped = true

# Available everywhere
macos = "10.0"
maccatalyst = "13.0"
ios = "2.0"
tvos = "9.0"
watchos = "2.0"
visionos = "1.0"
gnustep = true

# `objc_method_family`
# TODO: Move this
class.ABNewPersonViewController.methods.newPersonViewDelegate.skipped = true
