framework = "SecurityInterface"
crate = "objc2-security-interface"
# Require AppKit, since this framework is UI-heavy, and since it allows compiling less of AppKit
required-crates = ["objc2", "objc2-foundation", "objc2-app-kit"]
macos = "10.3"

# Uses NSCancelButton and NSOKButton, which are skipped in AppKit.
const.SFButtonTypeCancel.use-value = true
const.SFButtonTypeOK.use-value = true
