framework = "OSAKit"
crate = "objc2-osa-kit"
required-crates = ["objc2", "objc2-foundation", "objc2-app-kit"]
custom-lib-rs = true
macos = "10.4"

# Needs `Component` from Core Services / Carbon Core / Component Manager
class.OSALanguage.methods."initWithComponent:".skipped = true
class.OSALanguage.methods.componentInstance.skipped = true
class.OSALanguageInstance.methods.componentInstance.skipped = true
