framework = "SystemConfiguration"
crate = "objc2-system-configuration"
required-crates = ["objc2-core-foundation"]
custom-lib-rs = true
macos = "10.1"
maccatalyst = "13.0"
ios = "2.0"
tvos = "9.0"
visionos = "1.0"

# Needs AuthorizationRef from Security framework
fn.SCPreferencesCreateWithAuthorization.skipped = true

# Needs dispatch_queue_t from libdispatch
fn.SCDynamicStoreSetDispatchQueue.skipped = true
fn.SCNetworkConnectionSetDispatchQueue.skipped = true
fn.SCNetworkReachabilitySetDispatchQueue.skipped = true
fn.SCPreferencesSetDispatchQueue.skipped = true
