framework = "SceneKit"
crate = "objc2-scene-kit"
required-crates = ["objc2", "objc2-foundation"]
custom-lib-rs = true
macos = "10.8"
maccatalyst = "13.1"
ios = "8.0"
tvos = "9.0"
watchos = "3.0"
visionos = "1.0"

external.AVAudioEngine.module = "AVFAudio.AVAudioEngine"
external.AVAudioEnvironmentNode.module = "AVFAudio.AVAudioEnvironmentNode"
external.AVAudioNode.module = "AVFAudio.AVAudioNode"
external.JSContext.module = "JavaScriptCore.JSContext"

# Both protocol and class
protocol.SCNAnimation.renamed = "SCNAnimationProtocol"

# Needs SpriteKit (potential recursion, unsure which framework should depend on which)
protocol.SCNSceneRenderer.methods."presentScene:withTransition:incomingPointOfView:completionHandler:".skipped = true
protocol.SCNSceneRenderer.methods."overlaySKScene".skipped = true
protocol.SCNSceneRenderer.methods."setOverlaySKScene:".skipped = true

# Needs GLKVector3, GLKVector4 and GLKMatrix4 from GLKit
fn.SCNMatrix4ToGLKMatrix4.skipped = true
fn.SCNMatrix4FromGLKMatrix4.skipped = true
fn.SCNVector3FromGLKVector3.skipped = true
fn.SCNVector3ToGLKVector3.skipped = true
fn.SCNVector4FromGLKVector4.skipped = true
fn.SCNVector4ToGLKVector4.skipped = true

# Needs CGLContextObj from OpenGL, and NSOpenGLContext from AppKit
class.SCNRenderer.methods."rendererWithContext:options:".skipped = true
class.SCNView.methods.openGLContext.skipped = true
class.SCNView.methods."setOpenGLContext:".skipped = true
class.SCNView.methods.pixelFormat.skipped = true
class.SCNView.methods."setPixelFormat:".skipped = true
