framework = "AuthenticationServices"
crate = "objc2-authentication-services"
required-crates = ["objc2", "objc2-foundation", "objc2-app-kit"]
custom-lib-rs = true
macos = "10.15"
maccatalyst = "13.0"
ios = "12.0"
tvos = "13.0"
watchos = "6.0"
visionos = "1.0"

external.LAContext.module = "LocalAuthentication.LAContext"

# Uses a bit of complex feature testing setup, see ASFoundation.h
typedef.ASPresentationAnchor.skipped = true
typedef.ASViewController.skipped = true
typedef.ASImage.skipped = true

# The original superclass typedef is a bit difficult to extract from the
# superclass name, so let's do it manually.
class.ASCredentialProviderViewController.definition-skipped = true
class.ASAccountAuthenticationModificationViewController.definition-skipped = true

# Specifies superclass as UIControl or NSControl conditionally
class.ASAuthorizationAppleIDButton.definition-skipped = true

# header-translator incorrectly maps this as a method on `ASAuthorization`.
fn.ASAuthorizationAllSupportedPublicKeyCredentialDescriptorTransports.no-implementor = true
