framework = "VideoToolbox"
crate = "objc2-video-toolbox"
required-crates = ["objc2-core-foundation"]
custom-lib-rs = true
macos = "10.8"
maccatalyst = "13.0"
ios = "6.0"
tvos = "10.2"
visionos = "1.0"

# Wrongly renamed (Swift's renaming algorithm is insufficient)
const.kVTDecodeFrame_EnableAsynchronousDecompression.renamed = "Frame_EnableAsynchronousDecompression"
const.kVTDecodeFrame_DoNotOutputFrame.renamed = "Frame_DoNotOutputFrame"
const.kVTDecodeFrame_1xRealTimePlayback.renamed = "Frame_1xRealTimePlayback"
const.kVTDecodeFrame_EnableTemporalProcessing.renamed = "Frame_EnableTemporalProcessing"
