framework = "CoreText"
crate = "objc2-core-text"
required-crates = ["objc2-core-foundation"]
custom-lib-rs = true
macos = "10.8"
maccatalyst = "13.0"
ios = "3.2"
tvos = "9.0"
watchos = "2.0"
visionos = "1.0"

# Unknown calling convention / ABI
fn.CTRubyAnnotationCreate.skipped = true
typedef.BslnBaselineRecord.skipped = true

# Needs ATSFontRef from ATS framework
fn.CTFontGetPlatformFont.skipped = true
fn.CTFontCreateWithPlatformFont.skipped = true

# Emits -1 on an unsigned type
enum.CTFontUIFontType.constants.kCTFontUIFontNone.use-value = true
enum.CTRubyAlignment.constants.kCTRubyAlignmentInvalid.use-value = true
enum.CTRubyOverhang.constants.kCTRubyOverhangInvalid.use-value = true

# Emits 0x80000000 on an int
enum.anonymous.constants.kMORTLigLastAction.use-value = true
enum.anonymous.constants.kMORXCoverVertical.use-value = true
enum.anonymous.constants.kKERXVertical.use-value = true
