framework = "ImageIO"
crate = "objc2-image-io"
required-crates = ["objc2-core-foundation"]
custom-lib-rs = true
macos = "10.8"
maccatalyst = "13.0"
ios = "4.0"
tvos = "9.0"
watchos = "2.0"
visionos = "1.0"
