framework = "CoreWLAN"
crate = "objc2-core-wlan"
required-dependencies = ["objc2-foundation"]
custom-lib-rs = true
macos = "10.6"
maccatalyst = "13.0"

# Set counterparts
class.CWConfiguration.counterpart = "MutableSubclass(CoreWLAN::CWConfiguration::CWMutableConfiguration)"
class.CWMutableConfiguration.counterpart = "ImmutableSuperclass(CoreWLAN::CWConfiguration::CWConfiguration)"
class.CWNetworkProfile.counterpart = "MutableSubclass(CoreWLAN::CWNetworkProfile::CWMutableNetworkProfile)"
class.CWMutableNetworkProfile.counterpart = "ImmutableSuperclass(CoreWLAN::CWNetworkProfile::CWNetworkProfile)"

# Needs SecIdentityRef from Security
fn.CWKeychainCopyWiFiEAPIdentity.skipped = true
fn.CWKeychainSetWiFiEAPIdentity.skipped = true
fn.CWKeychainCopyEAPIdentity.skipped = true
fn.CWKeychainSetEAPIdentity.skipped = true
class.CWInterface.methods."associateToEnterpriseNetwork:identity:username:password:error:".skipped = true

# Needs `SFAuthorization` from the `SecurityFoundation` framework
class.CWInterface.methods."commitConfiguration:authorization:error:".skipped = true
