[package]
name = "test-fuzz"
version = "0.0.0"
publish = false
edition.workspace = true

[lints]
workspace = true

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
objc2 = { path = "../objc2" }
objc2-foundation = { path = "../../framework-crates/objc2-foundation", default-features = false, features = ["std"] }
objc2-core-foundation = { path = "../../framework-crates/objc2-core-foundation", default-features = false, features = ["std"] }
arbitrary = { version = "1", features = ["derive"] }
afl = { version = "0.15", optional = true }

[features]
gnustep-1-7 = ["objc2-foundation/gnustep-1-7"]
gnustep-1-8 = ["gnustep-1-7", "objc2-foundation/gnustep-1-8"]
gnustep-1-9 = ["gnustep-1-8", "objc2-foundation/gnustep-1-9"]
gnustep-2-0 = ["gnustep-1-9", "objc2-foundation/gnustep-2-0"]
gnustep-2-1 = ["gnustep-2-0", "objc2-foundation/gnustep-2-1"]

# Enable fuzzing with AFL
afl = ["dep:afl"]

# The features required for fuzzing all targets (used by CI)
fuzz-all = [
    "objc2-foundation/NSArray",
    "objc2-foundation/NSDictionary",
    "objc2-foundation/NSEnumerator",
    "objc2-foundation/NSNull",
    "objc2-foundation/NSObject",
    "objc2-foundation/NSSet",
    "objc2-foundation/NSString",
    "objc2-foundation/NSZone",
    "objc2-foundation/unstable-mutation-return-null",
    "objc2-core-foundation/CFString",
]

[[bin]]
name = "cfstring"
path = "fuzz_targets/cfstring.rs"
test = false
doc = false
bench = false
required-features = [
    "objc2-core-foundation/CFString",
]

[[bin]]
name = "class"
path = "fuzz_targets/class.rs"
test = false
doc = false
bench = false

[[bin]]
name = "sel"
path = "fuzz_targets/sel.rs"
test = false
doc = false
bench = false

[[bin]]
name = "encoding_parse"
path = "fuzz_targets/encoding_parse.rs"
test = false
doc = false
bench = false

[[bin]]
name = "nsstring"
path = "fuzz_targets/nsstring.rs"
test = false
doc = false
bench = false
required-features = ["objc2-foundation/NSString"]

[[bin]]
name = "collection_interior_mut"
path = "fuzz_targets/collection_interior_mut.rs"
test = false
doc = false
bench = false
required-features = [
    "objc2-foundation/NSDictionary",
    "objc2-foundation/NSEnumerator",
    "objc2-foundation/NSObject",
    "objc2-foundation/NSSet",
    "objc2-foundation/NSZone",
]

[[bin]]
name = "mut_while_iter"
path = "fuzz_targets/mut_while_iter.rs"
test = false
doc = false
bench = false
required-features = [
    "objc2-foundation/NSArray",
    "objc2-foundation/NSNull",
    "objc2-foundation/unstable-mutation-return-null",
]

[package.metadata.release]
release = false
