framework = "FileProviderUI"
crate = "objc2-file-provider-ui"
required-crates = ["objc2", "objc2-foundation", "objc2-file-provider"]
macos = "10.15"
maccatalyst = "15.0"
ios = "11.0"
visionos = "1.0"
