framework = "TVMLKit"
crate = "objc2-tv-ml-kit"
required-crates = ["objc2", "objc2-foundation"]
tvos = "9.0"

external.AVPlayer.module = "AVFoundation.AVPlayer"

# Swift renames "Self" to "none", so we do too.
const.TVElementUpdateTypeNone.renamed = "None"
const.TVElementUpdateTypeSubtree.renamed = "Subtree"
const.TVElementUpdateTypeStyles.renamed = "Styles"
const.TVElementUpdateTypeChildren.renamed = "Children"
const.TVElementUpdateTypeSelf.renamed = "Node"

# FIXME: Make header-translator pick this up from the explicit protocol impl.
class.TVBrowserTransitionAnimator.main-thread-only = true
