framework = "SoundAnalysis"
crate = "objc2-sound-analysis"
required-dependencies = ["objc2-foundation"]
macos = "10.15"
maccatalyst = "13.0"
ios = "13.0"
tvos = "13.0"
watchos = "9.0"
visionos = "1.0"

# Needs `AVFAudio` framework
class.SNAudioStreamAnalyzer.methods."initWithFormat:".skipped = true
class.SNAudioStreamAnalyzer.methods."analyzeAudioBuffer:atAudioFramePosition:".skipped = true
