framework = "IOBluetoothUI"
crate = "objc2-io-bluetooth-ui"
required-crates = ["objc2", "objc2-foundation", "objc2-app-kit"]
custom-lib-rs = true
macos = "10.2"

# TODO: Merge these somehow
typedef.IOBluetoothPairingControllerRef.renamed = "IOBluetoothPairingControllerRef"
typedef.IOBluetoothServiceBrowserControllerRef.renamed = "IOBluetoothServiceBrowserControllerRef"
typedef.IOBluetoothDeviceSelectorControllerRef.renamed = "IOBluetoothDeviceSelectorControllerRef"
