framework = "Accounts"
crate = "objc2-accounts"
required-crates = ["objc2", "objc2-foundation"]
macos = "10.8"
maccatalyst = "13.0"
ios = "5.0"

# Both enum and typedef
typedef.ACErrorCode.skipped = true
