framework = "QuickLook"
crate = "objc2-quick-look"
required-crates = ["objc2-core-foundation"]
custom-lib-rs = true
macos = "10.5"
maccatalyst = "13.0"
ios = "4.0"
visionos = "1.0"

# Needs libdispatch
fn.QLThumbnailDispatchAsync.skipped = true
