[features]
# Private framework functionality
#
# These functions/methods are all marked `unsafe`, since they may not always
# exist.
unstable-private = [
    "objc2-foundation/NSString",
    "objc2-foundation/NSError",
]
