framework = "AVKit"
crate = "objc2-av-kit"
required-dependencies = ["objc2-foundation"]
macos = "10.9"
maccatalyst = "13.0"
ios = "8.0"
tvos = "9.0"
watchos = "9.0"
visionos = "1.0"

# Has no declaration elsewhere, unknown where these actually come from
external.AVGroupExperienceCoordinator.module = "AVKit.AVPlayerViewController"
external.AVContentProposal.module = "AVKit.AVPlayerViewController"

# Needs AVCustomRoutingController from AVRouting
class.AVRoutePickerView.methods.customRoutingController.skipped = true
class.AVRoutePickerView.methods."setCustomRoutingController:".skipped = true
