framework = "ContactsUI"
crate = "objc2-contacts-ui"
required-crates = ["objc2", "objc2-foundation"]
macos = "10.11"
maccatalyst = "13.0"
ios = "9.0"
visionos = "1.0"

external.CNContact.module = "Contacts.CNContact"
external.CNContactProperty.module = "Contacts.CNContactProperty"
external.CNKeyDescriptor.module = "Contacts.CNContact"
