framework = "EventKit"
crate = "objc2-event-kit"
required-crates = ["objc2", "objc2-foundation"]
macos = "10.8"
maccatalyst = "13.0"
ios = "4.0"
watchos = "2.0"
visionos = "1.0"

external.NSColor.module = "AppKit.NSColor"
external.MKMapItem.module = "MapKit.MKMapItem"

# Needs the `AddressBook` framework
class.EKParticipant.methods."ABPersonInAddressBook:".skipped = true
