framework = "ScreenCaptureKit"
crate = "objc2-screen-capture-kit"
required-dependencies = ["objc2-foundation"]
custom-lib-rs = true
macos = "12.3"

# Needs `dispatch_queue_t`
class.SCStream.methods."addStreamOutput:type:sampleHandlerQueue:error:".skipped = true

# Needs AVFoundation
class.SCRecordingOutputConfiguration.methods.videoCodecType.skipped = true
class.SCRecordingOutputConfiguration.methods."setVideoCodecType:".skipped = true
class.SCRecordingOutputConfiguration.methods.outputFileType.skipped = true
class.SCRecordingOutputConfiguration.methods."setOutputFileType:".skipped = true
class.SCRecordingOutputConfiguration.methods.availableVideoCodecTypes.skipped = true
class.SCRecordingOutputConfiguration.methods.availableOutputFileTypes.skipped = true

# Needs CoreMedia
class.SCRecordingOutput.methods.recordedDuration.skipped = true
class.SCScreenshotManager.methods."captureSampleBufferWithFilter:configuration:completionHandler:".skipped = true
class.SCStreamConfiguration.methods.minimumFrameInterval.skipped = true
class.SCStreamConfiguration.methods."setMinimumFrameInterval:".skipped = true
class.SCStream.methods.synchronizationClock.skipped = true
protocol.SCStreamOutput.methods."stream:didOutputSampleBuffer:ofType:".skipped = true
