framework = "SpriteKit"
crate = "objc2-sprite-kit"
required-crates = ["objc2", "objc2-foundation"]
macos = "10.9"
maccatalyst = "13.0"
ios = "7.0"
tvos = "9.0"
watchos = "10.0"
visionos = "1.0"

external.AVPlayer.module = "AVFoundation.AVPlayer"
external.AVAudioNode.module = "AVFAudio.AVAudioNode"
external.AVAudioEngine.module = "AVFAudio.AVAudioEngine"

# Needs SceneKit (potential recursion, unsure which framework should depend on which)
class.SK3DNode.methods.scnScene.skipped = true
class.SK3DNode.methods."setScnScene:".skipped = true
class.SK3DNode.methods."hitTest:options:".skipped = true
class.SK3DNode.methods.pointOfView.skipped = true
class.SK3DNode.methods."setPointOfView:".skipped = true

# Custom simd definition
typedef.vector_float3.skipped = true

# Needs GLKVector*/GLKMatrix* from GLKit
class.SKUniform.methods.floatVector2Value.skipped = true
class.SKUniform.methods."setFloatVector2Value:".skipped = true
class.SKUniform.methods.floatVector3Value.skipped = true
class.SKUniform.methods."setFloatVector3Value:".skipped = true
class.SKUniform.methods.floatVector4Value.skipped = true
class.SKUniform.methods."setFloatVector4Value:".skipped = true
class.SKUniform.methods.floatMatrix2Value.skipped = true
class.SKUniform.methods."setFloatMatrix2Value:".skipped = true
class.SKUniform.methods.floatMatrix3Value.skipped = true
class.SKUniform.methods."setFloatMatrix3Value:".skipped = true
class.SKUniform.methods.floatMatrix4Value.skipped = true
class.SKUniform.methods."setFloatMatrix4Value:".skipped = true
class.SKUniform.methods."uniformWithName:floatVector2:".skipped = true
class.SKUniform.methods."uniformWithName:floatVector3:".skipped = true
class.SKUniform.methods."uniformWithName:floatVector4:".skipped = true
class.SKUniform.methods."uniformWithName:floatMatrix2:".skipped = true
class.SKUniform.methods."uniformWithName:floatMatrix3:".skipped = true
class.SKUniform.methods."uniformWithName:floatMatrix4:".skipped = true
class.SKUniform.methods."initWithName:floatVector2:".skipped = true
class.SKUniform.methods."initWithName:floatVector3:".skipped = true
class.SKUniform.methods."initWithName:floatVector4:".skipped = true
class.SKUniform.methods."initWithName:floatMatrix2:".skipped = true
class.SKUniform.methods."initWithName:floatMatrix3:".skipped = true
class.SKUniform.methods."initWithName:floatMatrix4:".skipped = true
