framework = "SpriteKit"
crate = "objc2-sprite-kit"
required-crates = ["objc2", "objc2-foundation"]
undesired-default-dependencies = ["objc2-open-gl", "objc2-gl-kit"] # OpenGL is deprecated
macos = "10.9"
maccatalyst = "13.0"
ios = "7.0"
tvos = "9.0"
watchos = "10.0"
visionos = "1.0"

external.AVPlayer.module = "AVFoundation.AVPlayer"
external.AVAudioNode.module = "AVFAudio.AVAudioNode"
external.AVAudioEngine.module = "AVFAudio.AVAudioEngine"

# Needs SceneKit (potential recursion, unsure which framework should depend on which)
class.SK3DNode.methods.scnScene.skipped = true
class.SK3DNode.methods."setScnScene:".skipped = true
class.SK3DNode.methods."hitTest:options:".skipped = true
class.SK3DNode.methods.pointOfView.skipped = true
class.SK3DNode.methods."setPointOfView:".skipped = true

# Custom simd definition
typedef.vector_float3.skipped = true
