framework = "CryptoTokenKit"
crate = "objc2-crypto-token-kit"
required-crates = ["objc2", "objc2-foundation"]
macos = "10.10"
maccatalyst = "13.0"
ios = "13.0"
tvos = "13.0"
watchos = "8.0"
visionos = "1.0"
