framework = "MetricKit"
crate = "objc2-metric-kit"
required-crates = ["objc2", "objc2-foundation"]
macos = "12.0"
maccatalyst = "13.0"
ios = "13.0"
visionos = "1.0"

# `os_log_t` not defined; skip for now
class.MXMetricManager.methods."makeLogHandleWithCategory:".skipped = true

# Private
fn._MXSignpostMetricsSnapshot.skipped = true
