framework = "IOUSBHost"
crate = "objc2-io-usb-host"
required-crates = ["objc2", "objc2-foundation"]
custom-lib-rs = true
macos = "10.15"
maccatalyst = "14.0"

# Return type marked as non-null, raises `unknown error result type`.
class.IOUSBHostControllerInterface.methods."getPortStateMachineForCommand:error:".skipped = true
class.IOUSBHostControllerInterface.methods."getPortStateMachineForPort:error:".skipped = true

# Returns non-object pointer in error method, raises `unknown error result type`.
class.IOUSBHostObject.methods."descriptorWithType:length:index:languageID:requestType:requestRecipient:error:".skipped = true
class.IOUSBHostObject.methods."descriptorWithType:length:index:languageID:error:".skipped = true
class.IOUSBHostObject.methods."descriptorWithType:length:error:".skipped = true
class.IOUSBHostObject.methods."configurationDescriptorWithIndex:error:".skipped = true
class.IOUSBHostObject.methods."configurationDescriptorWithConfigurationValue:error:".skipped = true

# Needs uuid_t, unsure about the ABI.
fn.IOUSBGetPlatformCapabilityDescriptorWithUUID.skipped = true

# Declared twice.
static.IOUSBHostMatchingPropertyKeyProductIDMask.skipped = true

# Value taken from a type that is c_uint internally.
const.IOUSBHostCITransferCompletionMessageControlStatus.use-value = true
const.IOUSBHostCITransferCompletionMessageControlStatusPhase.use-value = true

# Overflows while calculating on 32-bit.
const.IOUSBHostCIEndpointCreateCommandData1Descriptor.skipped = true
const.IOUSBHostCIEndpointUpdateCommandData1Descriptor.skipped = true
const.IOUSBHostCIEndpointSetNextTransferCommandData1Address.skipped = true
const.IOUSBHostCISetupTransferData1wIndex.skipped = true
const.IOUSBHostCISetupTransferData1wLength.skipped = true
const.IOUSBHostCITransferCompletionMessageData1TransferStructure.skipped = true
